[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true
priority=10

[program:xray]
command=xray run -config /usr/local/etc/xray/config.json
autorestart=true
priority=20

[program:badvpn]
command=badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 40 --loglevel warning
autorestart=true
priority=30

[program:anti_ddos_bridge]
command=python3 /usr/local/bin/anti_ddos.py
autorestart=true
priority=40

[program:sub_server]
command=python3 /usr/local/bin/sub_server.py
autorestart=true
priority=45

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
priority=50
